### ISSUE TITLE
It cannot be used after the deployment is complete

### ISSUE THREAD

**Issue by Juddd** [webtor-io/self-hosted#7]
There were no errors when I started the project. Could you provide a more detailed documentation? What are the relationships between these components, and how should they be deployed? This is my current `docker-compose.yml` file:

```
version: '3'
services:
  webtor:
    image: ghcr.io/webtor-io/self-hosted:latest
    container_name: webtor
    restart: always
    ports:
      - "8086:8080"
    volumes:
      - /volume1/video/webtortmp:/data
    environment:
      - TORRENT_WEB_SEEDER_URL=http://torrent-web-seeder:8080
      - TORRENT_STORE_SERVICE=torrent-store:50051
      - EXTERNAL_HOST=192.168.3.177:8080
    depends_on:
      - torrent-web-seeder
      - torrent-store
      - torrent-http-proxy

  torrent-store:
    image: ghcr.io/webtor-io/torrent-store:latest
    container_name: torrent-store
    restart: always
    expose:
      - "50051"
    volumes:
      - /volume1/docker/webtor/torrent-metadata:/data

  torrent-web-seeder:
    image: ghcr.io/webtor-io/torrent-web-seeder:latest
    container_name: torrent-web-seeder
    restart: always
    depends_on:
      - torrent-store
    ports:
      - "3002:8080"
    environment:
      - TORRENT_STORE_SERVICE=torrent-store:50051
      - HTTP_PROXY=http://192.168.3.177:7890
      - HTTPS_PROXY=http://192.168.3.177:7890
      - http_proxy=http://192.168.3.177:7890
      - https_proxy=http://192.168.3.177:7890
    volumes:
      - /volume1/video/webtortmp:/data

  torrent-http-proxy:
    image: ghcr.io/webtor-io/torrent-http-proxy:latest
    container_name: torrent-http-proxy
    restart: always
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/config/config.yaml
    volumes:
      - /volume1/docker/webtor/config.yaml:/config/config.yaml
    depends_on:
      - torrent-web-seeder
      - torrent-store

```

This is my `config.yaml` file:
```
torrent_http_proxy:
  listen_port: 8080
  seeder_url: http://torrent-web-seeder:8080
  storage_service_url: http://torrent-store:50051
  proxy:
    http_proxy: http://192.168.3.177:7890
    https_proxy: http://192.168.3.177:7890

services:
  torrent-web-seeder:
    url: http://torrent-web-seeder:8080

  torrent-store:
    url: http://torrent-store:50051
```

However, I am unable to use your webtor to download magnet links or .torrent files. Even after downloading, I only get a video file that cannot be opened and is empty.

**Comment by vintikzzz** [comment]
Hi! You don't have to use `docker-compose`, all dependencies are included in `self-hosted` image. Just try to install it through the doumentation in `README.md`

**Comment by Juddd** [comment]
I originally deployed your self-hosted image separately using the following configuration:
```
version: '3'

services:
  webtor:
    image: ghcr.io/webtor-io/self-hosted:latest
    container_name: webtor
    restart: always
    environment:
      - HTTP_PROXY=http://192.168.3.177:7890
      - HTTPS_PROXY=http://192.168.3.177:7890
      - http_proxy=http://192.168.3.177:7890
      - https_proxy=http://192.168.3.177:7890
    ports:
      - 8080:8080
    volumes:
      - /volume1/video/webtortmp:/data
```

However, I noticed that when I access `http://192.168.3.177:8080/` and click *"Try demo1!"→"Download [129 MB]"→"Start download"*, it redirects to a page like the one shown in the screenshot. I suspect that my service setup might be incomplete, which is why I started looking into your `torrent-web-seeder` and `torrent_http_proxy` projects.

Could you please help me analyze where the issue might be?

![Image](https://github.com/user-attachments/assets/275c18de-7b93-4ada-a579-6c99313018fe)

**Comment by vintikzzz** [comment]
I don' really understand why are you using environment variables in your `docker-compose` file.
So your file should be
```yaml
version: '3'

services:
  webtor:
    image: ghcr.io/webtor-io/self-hosted:latest
    container_name: webtor
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /volume1/video/webtortmp:/data
```

`torrent-http-proxy` is internal service inside main contatiner, so you don't have to to add additional deps anyway.
I have tried to setup on different devices and all works as expected. Can you provide container logs?
