### ISSUE TITLE
[Domain Issue] Webtor tries to fetch media from localhost:8080 after the Stream button is pressed.

### ISSUE THREAD

**Issue by VladyslavDobrovolskyi** [webtor-io/self-hosted#8]
In the scenario where I don't specify the DOMAIN in the docker-compose file, the result is that the application tries to reach torrent-http-proxy at localhost:8080,

But when I specify the DOMAIN, I get the following:
- Retrieving resource data done
- Retrieving stream url error
- Failed to retrieve stream url

and I can't reach the stage of downloading through torrent-http-proxy...

--- 

Can you advise me on how I can resolve this? I'm leaning towards leaving the DOMAIN configuration empty and overriding localhost for torrent-http-proxy inside the container, but so far I haven't found the right approach for that

**Comment by vintikzzz** [comment]
By default, the DOMAIN is set to `http://localhost:8080`. If you’re accessing the UI from a different IP or domain, don’t forget to update the DOMAIN setting accordingly — otherwise streaming won’t work.

**Comment by vedhavyas** [comment]
I have add DOMAIN to the docker env.
I have a custom domain and caddy reverse proxy. 
The domain I have set for webtor is https://webtor.hub

When I click stream, I see the following in the docker logs
[web-ui] time="2025-09-30T17:06:57Z" level=error msg="got job error" error="failed to retrieve stream url: Get \"https://webtor.hub/torrent-http-proxy/78e6416923ce868581d852a7d742747d4e8eaeb1/somthing.mkv?api-key=<API_KEY>&done=true&token=<TOKEN>\": dial tcp: lookup webtor.hub on 127.0.0.11:53: no such host

**Comment by vintikzzz** [comment]
no it shouldn't, it tries to resolve [webtor.hub](https://webtor.hub/) as it was designed in distributed environment... I have another issue about that. I have to figure out how to solve this somehow

**Comment by vedhavyas** [comment]
is there a docker-compose example I can use instead of single docker image ?
Single docker does not seems to work

**Comment by vedhavyas** [comment]
Finally made it work.

For anyone using caddy as reverse proxy with self signed certs and custom tld, the following docker compose service worked

```
  webtor:
    container_name: webtor
    image: ghcr.io/webtor-io/self-hosted:latest
    hostname: webtor
    # extra hosts for webtor.hub so that dns resolves to caddy
    extra_hosts:
      # caddy static IP
      - "webtor.hub:10.10.2.4"
    environment:
      - DOMAIN=https://webtor.hub
      - CLEANER_FREE=5G
      - CLEANER_KEEP_FREE=10G
      # webtor Go SSL ROOT cert override pointing to caddy root cert
      - SSL_CERT_FILE=/caddy_certs/caddy/pki/authorities/local/root.crt
    volumes:
      - /webtor/data:/data
      # caddy certs location for SSL cert check
      - /caddy_data/:/caddy_certs:ro
    networks:
      # webtor should be able to communicate with caddy. So it should be accesible
      # with same network but as long as webtor docker can reach to caddy docker, it should work
      - caddy-network
    labels:
      caddy: webtor.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 8080}}"
```
